name: "samsamoohooh"
listen: "0.0.0.0:80"
env: "dev"

postgres:
  host: "localhost"
  user: "postgres"
  port: 5432
  password: "Qwe123!"
  dbName: "samsamoohooh"
  options:
    maxIdleConns: 10
    maxOpenConns: 100
    connMaxLifetime: "30m"

jwt:
  secret: "j1pVm3mSCqAsTzYDljBwJhIMJl1ip6TPfthlUbRLBxbM9LVjLBADqwj3DA6wCrZP"
  duration: "8760h" # 365 day