definitions:
  apperr.Apperr:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
  domain.CreateUserRequest:
    properties:
      biography:
        maxLength: 7
        type: string
      nickname:
        type: string
    required:
    - nickname
    type: object
  domain.CreateUserResponse:
    properties:
      biography:
        type: string
      nickname:
        type: string
      userID:
        type: integer
    type: object
info:
  contact: {}
paths:
  /users:
    post:
      consumes:
      - application/json
      description: 새로운 사용자 생성 API
      parameters:
      - description: 새로운 사용자 정보
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/domain.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 성공적으로 사용자를 생성한 경우
          schema:
            $ref: '#/definitions/domain.CreateUserResponse'
        "409":
          description: 이미 존재하는 사용자가 있는 경우
          schema:
            $ref: '#/definitions/apperr.Apperr'
      summary: 새로운 사용자 생성 ✅
      tags:
      - users
swagger: "2.0"
