// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "로그인 ✅",
                "parameters": [
                    {
                        "description": "로그인에 필요한 정보",
                        "name": "LoginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공적으로 로그인을 성공한 경우",
                        "schema": {
                            "$ref": "#/definitions/domain.LoginResponse"
                        }
                    }
                }
            }
        },
        "/auth/validate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "유효성 검증 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 토큰",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공적으로 유효성 검증을 성공한 경우",
                        "schema": {
                            "$ref": "#/definitions/domain.ValidateResponse"
                        }
                    }
                }
            }
        },
        "/goals": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "목표 목록 조회 ✅",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "name": "groupID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 300,
                        "minimum": 1,
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "목표 목록 조회 성공",
                        "schema": {
                            "$ref": "#/definitions/domain.ListGoalsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "새로운 목표 생성 ✅",
                "parameters": [
                    {
                        "description": "생성할 목표 정보",
                        "name": "CreateGoalReqeust",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateGoalRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "성공적으로 목표를 생성한 경우",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateGoalResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "목표 삭제 ✅",
                "parameters": [
                    {
                        "description": "삭제할 목표 정보",
                        "name": "DeleteGoalRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.DeleteGoalRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/goals/{goalID}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "목표 정보 수정 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "수정할 목표 ID",
                        "name": "goalID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "수정할 목표 정보",
                        "name": "PatchGoalRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PatchGoalRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/groups": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "모임 리스트 ✅",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "조회할 모임 개수",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공적으로 모임 리스트를 조회한 경우",
                        "schema": {
                            "$ref": "#/definitions/domain.ListGroupsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "새로운 모임 생성 ✅",
                "parameters": [
                    {
                        "description": "생성할 모임 정보",
                        "name": "CreateGroupRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "성공적으로 모임을 생성한 경우",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateGroupResponse"
                        }
                    }
                }
            }
        },
        "/groups/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "모임 참가 ✅",
                "parameters": [
                    {
                        "description": "참여할 모임 정보",
                        "name": "JoinGroupRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.JoinGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/groups/leave": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "모임 탈퇴 ✅",
                "parameters": [
                    {
                        "description": "탈퇴할 모임 정보",
                        "name": "LeaveGroupRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LeaveGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/groups/{groupID}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "모임 정보 수정 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "수정할 모임 ID",
                        "name": "groupID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "수정할 모임 정보",
                        "name": "PatchGroupRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PatchGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/topics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topics"
                ],
                "summary": "주제 목록 조회 ✅",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "name": "goalID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 300,
                        "minimum": 1,
                        "type": "integer",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "주제 목록 조회 성공",
                        "schema": {
                            "$ref": "#/definitions/domain.ListTopicsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topics"
                ],
                "summary": "새로운 주제 생성 ✅",
                "parameters": [
                    {
                        "description": "생성할 주제 정보",
                        "name": "CreateTopicReqeust",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateTopicRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "성공적으로 주제를 생성한 경우",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateTopicResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topics"
                ],
                "summary": "주제 삭제 ✅",
                "parameters": [
                    {
                        "description": "삭제할 주제 정보",
                        "name": "DeleteTopicRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.DeleteTopicRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/topics/{topicID}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topics"
                ],
                "summary": "주제 정보 수정 ✅",
                "parameters": [
                    {
                        "type": "string",
                        "description": "수정할 목표 ID",
                        "name": "goalID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "수정할 주제 정보",
                        "name": "PatchTopicRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PatchTopicRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "새로운 사용자 생성 ✅",
                "parameters": [
                    {
                        "description": "생성할 사용자 정보",
                        "name": "CreateUserRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "성공적으로 사용자를 생성한 경우",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateUserResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "사용자 삭제 ✅",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "사용자 정보 수정 ✅",
                "parameters": [
                    {
                        "description": "수정할 사용자 정보",
                        "name": "PatchUserRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PatchUserRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CreateGoalRequest": {
            "type": "object",
            "required": [
                "deadline",
                "groupID",
                "page"
            ],
            "properties": {
                "deadline": {
                    "type": "string"
                },
                "groupID": {
                    "type": "integer",
                    "minimum": 1
                },
                "page": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "domain.CreateGoalResponse": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string"
                },
                "goalID": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                }
            }
        },
        "domain.CreateGroupRequest": {
            "type": "object",
            "required": [
                "bookAuthor",
                "bookMaxPage",
                "bookTitle"
            ],
            "properties": {
                "bookAuthor": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "bookMaxPage": {
                    "type": "integer",
                    "minimum": 1
                },
                "bookPublisher": {
                    "type": "string",
                    "maxLength": 255
                },
                "bookTitle": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "introduction": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "domain.CreateGroupResponse": {
            "type": "object",
            "properties": {
                "bookAuthor": {
                    "type": "string"
                },
                "bookCurrentPage": {
                    "type": "integer"
                },
                "bookMaxPage": {
                    "type": "integer"
                },
                "bookPublisher": {
                    "type": "string"
                },
                "bookTitle": {
                    "type": "string"
                },
                "groupID": {
                    "type": "integer"
                },
                "introduction": {
                    "type": "string"
                }
            }
        },
        "domain.CreateTopicRequest": {
            "type": "object",
            "required": [
                "content",
                "goalID",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 4
                },
                "goalID": {
                    "type": "integer",
                    "minimum": 1
                },
                "title": {
                    "type": "string",
                    "maxLength": 46,
                    "minLength": 4
                }
            }
        },
        "domain.CreateTopicResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "topicID": {
                    "type": "integer"
                }
            }
        },
        "domain.CreateUserRequest": {
            "type": "object",
            "required": [
                "nickname"
            ],
            "properties": {
                "biography": {
                    "type": "string",
                    "maxLength": 14
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 2
                }
            }
        },
        "domain.CreateUserResponse": {
            "type": "object",
            "properties": {
                "biography": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "domain.DeleteGoalRequest": {
            "type": "object",
            "properties": {
                "goalID": {
                    "type": "integer"
                }
            }
        },
        "domain.DeleteTopicRequest": {
            "type": "object",
            "required": [
                "topicID"
            ],
            "properties": {
                "topicID": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "domain.GoalResponse": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string"
                },
                "goalID": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                }
            }
        },
        "domain.GroupResponse": {
            "type": "object",
            "properties": {
                "bookAuthor": {
                    "type": "string"
                },
                "bookCurrentPage": {
                    "type": "integer"
                },
                "bookMaxPage": {
                    "type": "integer"
                },
                "bookPublisher": {
                    "type": "string"
                },
                "bookTitle": {
                    "type": "string"
                },
                "groupID": {
                    "type": "integer"
                },
                "introduction": {
                    "type": "string"
                }
            }
        },
        "domain.JoinGroupRequest": {
            "type": "object",
            "required": [
                "groupIDs"
            ],
            "properties": {
                "groupIDs": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "domain.LeaveGroupRequest": {
            "type": "object",
            "required": [
                "groupIDs"
            ],
            "properties": {
                "groupIDs": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "domain.ListGoalsResponse": {
            "type": "object",
            "properties": {
                "goals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GoalResponse"
                    }
                }
            }
        },
        "domain.ListGroupsResponse": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GroupResponse"
                    }
                }
            }
        },
        "domain.ListTopicsResponse": {
            "type": "object",
            "properties": {
                "topics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.TopicResponse"
                    }
                }
            }
        },
        "domain.LoginRequest": {
            "type": "object",
            "required": [
                "nickname"
            ],
            "properties": {
                "nickname": {
                    "type": "string"
                }
            }
        },
        "domain.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "domain.PatchGoalRequest": {
            "type": "object",
            "required": [
                "goalID"
            ],
            "properties": {
                "deadline": {
                    "type": "string"
                },
                "goalID": {
                    "type": "integer",
                    "minimum": 1
                },
                "page": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "domain.PatchGroupRequest": {
            "type": "object",
            "required": [
                "grouopID"
            ],
            "properties": {
                "bookAuthor": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "bookCurrentPage": {
                    "type": "integer",
                    "minimum": 1
                },
                "bookMaxPage": {
                    "type": "integer",
                    "minimum": 1
                },
                "bookPublisher": {
                    "type": "string",
                    "maxLength": 255
                },
                "bookTitle": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "grouopID": {
                    "type": "integer",
                    "minimum": 1
                },
                "introduction": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "domain.PatchTopicRequest": {
            "type": "object",
            "required": [
                "topicID"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 4
                },
                "title": {
                    "type": "string",
                    "maxLength": 46,
                    "minLength": 4
                },
                "topicID": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "domain.PatchUserRequest": {
            "type": "object",
            "properties": {
                "biography": {
                    "type": "string",
                    "maxLength": 14
                },
                "nickname": {
                    "description": "updates",
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 2
                }
            }
        },
        "domain.TopicResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "topicID": {
                    "type": "integer"
                }
            }
        },
        "domain.ValidateResponse": {
            "type": "object",
            "properties": {
                "biography": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
